name: Sync README

on:
  push:
    paths:
      - 'docs/en-us/README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy README file
        run: |
          cp docs/en-us/README.md README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Sync README.md
          branch: main
